### ISSUE TITLE
Package for Void linux

### ISSUE THREAD

**Issue by ghost** [nroi/waitforfile#1]
Hi !

Today I created a template, the equivalent of a PKGBUILD in Arch, to build a package for Void linux.

I made a [pull request](https://github.com/voidlinux/void-packages/pull/10822), I hope that it will be accepted.

Your program is very useful, thank you.

In the releases, I was pleasantly surprised to find precompiled binaries for **musl** ! 👍 

Void linux is a distribution which offers musl and glibc.

**Comment by nroi** [comment]
Awesome! Thanks for letting me know.
I'll keep an eye on the pull request and close issue this as soon as a decision has been made.

**Comment by ghost** [comment]
However, in the releases, concerning this one:

`arm-unknown-linux-gnueabi`

hard float could not be possible ?

Thanks.

**Comment by nroi** [comment]
@cr6git I wouldn't know how. I tried just adding `arm-unknown-linux-gnueabihf` as target, but it won't build due to missing crates: https://travis-ci.org/nroi/waitforfile/jobs/329020999
In case anyone wants to do any further research on this, check out [trust](https://github.com/japaric/trust). I'm using travis to build the binaries and I just copied the travis config files from trust.

**Comment by ghost** [comment]
My pull request has been accepted and merged! 😄 

`xbps-install -S waitforfile`

**Comment by nroi** [comment]
Great, thanks again.
